# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Jarme"
description: > # this means to ignore newlines until "email:"
   All About Memories In A Jar.

email: jarmeapp@gmail.com
#blog logo
logo: "/assets/images/logo_large.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'JarmeApp'
author: 'JarmeApp'
author_image: "/assets/images/logo_medium.png"

paginate:	8

url: "https://blog.jarmemori.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jarmeapp'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jarmeapp
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/jarmeapp
    desc: Connect with us facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/foysalit
    desc:	Fork us on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
